# Generated by Django 5.2.7 on 2025-11-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='users',
            new_name='user',
        ),
    ]
